### ISSUE TITLE
no way to call a smart contract?

### ISSUE THREAD

**Issue by ctzurcanu** [lambda-mechanics/Web3.jl#2]
I see no mechanism in the doc. Is this lib still maintained or even used by somebody?

**Comment by zot** [comment]
I have a few improvements and an example contract, along with a Julia version of keccak.

I'll test and commit today

**Comment by zot** [comment]
I haven't had time to test it but I did push a new branch with the example code in it.  Here's an example of how to access a smart contract: https://github.com/lambda-mechanics/Web3.jl/blob/julia-keccak/example/julia/dumpContract.jl

You use `ContractContext(connection, contractid, abifilename)` to make a `ContractContext` and it behaves like an object -- you say `context.bob("hello")` to call the `bob` function in the smart contract with `"hello"`. The code compiles a Julia function for each contract function so you can call it.

I'm not sure if I like the name `ContractContext` -- I named it that because Contract holds a reference to the contract itself and I wrote ContractContext later. I think maybe I'll rename `Contract` to `ContractDefinition` and rename `ContractContext` to just `Contract`.

You can make a`Contract` (or maybe `ContractDefinition`) just from an ABI file -- you don't need a connection to an Ethereum node for that. `ContractContext` holds a `Contract` and a `Connection`.

To get started, you can use dumpContract.jl as a template and plug in your own contract's ID and ABI filename. abifile should just hold the pathname. I put that join and split in there as a cheap way to make my path with slashes in it work on both Linux and Windows but for your own tests, you probably wouldn't need that.

**Comment by ctzurcanu** [comment]
Nice to see things moving again with Web3.jl.
I am new to Julia, so I do not know what these errors mean exactly:
As much as I tried, I could not get it to work for me:
(using the julia-keccak branch with ):

import Pkg; Pkg.add(Pkg.PackageSpec(url="https://github.com/lambda-mechanics/Web3.jl", rev="julia-keccak"))

import Web3

┌ Info: Precompiling Web3 [0881af41-a624-557c-96ff-9a730c8d7287]
└ @ Base loading.jl:1260
ERROR: LoadError: invalid redefinition of constant keccak
Stacktrace:
 [1] top-level scope at /Users/user/.julia/packages/Web3/OQYE3/src/Web3.jl:145
 [2] include(::Module, ::String) at ./Base.jl:377
 [3] top-level scope at none:2
 [4] eval at ./boot.jl:331 [inlined]
 [5] eval(::Expr) at ./client.jl:449
 [6] top-level scope at ./none:3
in expression starting at /Users/user/.julia/packages/Web3/OQYE3/src/Web3.jl:145
Failed to precompile Web3 [0881af41-a624-557c-96ff-9a730c8d7287] to /Users/user/.julia/compiled/v1.4/Web3/lJ3rO_0jJQj.ji.

Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1272
 [3] _require(::Base.PkgId) at ./loading.jl:1029
 [4] require(::Base.PkgId) at ./loading.jl:927
 [5] require(::Module, ::Symbol) at ./loading.jl:922
 [6] top-level scope at In[2]:1

**Comment by zot** [comment]
OK, fixed that error -- tuples in Julia require at least one comma, like this (1, 2, 3) or (1,), and when I took out all but one value, I forgot to leave a comma in at the end. I use named tuples like inline structures sometimes in my code because you can access them with dots. So if you say

```
const a = (b = 1, c = (d = 2, e = 3))
```
You can use `a.b`, `a.c.d`, etc. Kind of like this JavaScript code:
```
const a = {b: 1, c: {d: 2, e: 3}};
```
except that Julia named tuples are fully immutable so you can't reassign a.b like you could in JavaScript (assuming you're not freezing the object, which would be a lot more wordy). Also the Julia code is fully inlined and the paths should all compile out and be replaced just with the constants.

---
Now that the Julia code actually loads, however, I'm getting another error from Ethereum. Could be a problem with my serialization. I'll look at that this weekend.

Feel free to take a look if you have time before I get to it this weekend. This code's not exactly beginner Julia code though :).

**[EDIT]** By the way, I did test the `numAccounts` function in Remix and it seems to work properly, which is why I think the error is in my serialization code, not in my Solidity account example code.

**Comment by ctzurcanu** [comment]
yes. in Remix works. in Web3.jl:
"Call numAccounts in contract 2208b998bac9B1F0246915629ac274cBe7e5C81e
ERROR: VM Exception while processing transaction: revert
RuntimeError: VM Exception while processing transaction: revert
    at Function.RuntimeError.fromResults (/Applications/Ganache.app/Contents/Resources/static/node/node_modules/ganache-core/lib/utils/runtimeerror.js:89:13)"

I'd love to see a resolution ASAP on this. I appreciate the keccak in Julia. Congrats if it is your implementation.
Also: I did not find the Domdom pak in Julia to see what your example intents. I am not even sure if I should write another issue about that.

**Comment by ctzurcanu** [comment]
It really needs a `call` function. Even for `send` it did not calculate the `data` correctly.
I parroted the send and made a call for 0-arity functions: 

```
function call(context::ContractContext, name, from, args, options...)
    println("Call $name in contract $(contract(context).id) ",encodearguments(args))
    func = Web3.functions(context)[name]
    transaction = merge!(Dict([
        :to => contract(context).id 
        :from => from
        :data=> bytes2hex(keccak(collect(UInt8, "$name($(join(repr.(func.argtypes), ",")))"), 32))[1:8] ]), pairs(options))
    result = rawjsonget(connection(context).url, :eth_call, transaction)
    if haskey(result, "error")
        err = result["error"]
        println("ERROR: $(err["message"])\n$(err["data"]["stack"])")
    end
    println("JSON: $(repr(result))")
    result
end
```

and it worked! so your `keccak` is good :)
I'm very impatient to see a stable release of this!

**Comment by zot** [comment]
> I'd love to see a resolution ASAP on this

Well, I love for things to be done by other people ASAP, too :). I'm taking a look at it right now -- hopefully I'll be able to fix it without too much trouble.

> I appreciate the keccak in Julia. Congrats if it is your implementation.

It's a port of https://github.com/mjosaarinen/tiny_sha3 to Julia (MIT License) but I neglected to cite the original in my code -- that's fixed for the next commit. Finding an implementation with parameters that actually line up with what Ethereum uses, as opposed to SHA3 was a royal pain!

> Also: I did not find the Domdom pak in Julia to see what your example intents. I am not even sure if I should write another issue about that.

No, I made this commit just for you -- it's not actually ready yet. I made Web3.jl because someone has shown interest in doing a blockchain project with me and I'd like to write the backend in Julia but I couldn't find the equivalent of Web3.js for Julia. That project has stalled though and I haven't worked on this for a while (as you can tell from the commits).

One of my goals was/is to make a tiny example Julia-based DApp to manage "user accounts" stored on the blockchain so people can get some idea of how to do things like that.

Domdom is, another project of mine, is [here](https://github.com/zot/domdom) if you'd like to check it out. This also grew out of the potential blockchain project and has also stalled a bit :).

**Comment by ctzurcanu** [comment]
Sorry if I seemed to take advantage (but of course I will :D ). I am willing to help as much as I can. How about if I do the other methods if you get done `send` and `call` ? So I can have some examples I can extend while learning Julia.

**Comment by zot** [comment]
That'd be great -- I'm working on call right now. Send will be after that :)

**Comment by zot** [comment]
Pushed the latest I have -- ContractContext is a convenience layer I had started on around the same time as my Julia port of keccak. `dumpContract` has some example calls at the bottom, including a commented out use of send:

```
context.updateAccount.send(true, "d", "e", "f", from = "0x579CDD2D6404f033E70336BDE7a30CDf5c2c574c", gas = 200000)
```
That creates a "user account" named d with password e and full name f.

I still need to deserialize return values, so the final test call to getAccount.call("d") doesn't return a friendly Julia tuple yet, just the JSON value. I should have that working in the next day or so, I should think...

**Comment by zot** [comment]
OK, pushed what seems to work for send() and call(). I haven't extensively tested this and haven't written any more docs.

Please see dumpContract.jl for examples of how to use send() and call() and give me some feedback on what you think about its usability.

**Comment by ctzurcanu** [comment]
Thank you. I will begin to look at it later today.

**Comment by zot** [comment]
Merged it into the master

**Comment by zot** [comment]
OK, since calling smart contracts ostensibly works, I'm closing this.
